fn p1(bar: u64) -> u64 {
    /// If we list all the natural numbers below 10 that are multiples of 3 or 5,
    /// we get 3, 5, 6 and 9. The sum of these multiples is 23.
    /// Find the sum of all the multiples of 3 or 5 below 1000.");
    let mut n = 1;
    let mut agg = 0;
    loop {
        if n == bar {
            break;
        }
        if n % 3 == 0 || n % 5 == 0 {
            agg += n;
        }
        n += 1;
    }
    agg
}

#[test]
fn test_p1() {
    assert!(p1(10) == 23)
}

fn p1_iterate(bar: u64) -> u64 {
    (1..bar).filter(|n| n % 3 == 0 || n % 5 == 0).sum()
}

#[test]
fn test_p1_iterate() {
    assert!(p1_iterate(10) == 23)
}

fn p2() -> u64 {
    ///  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    ///  By starting with 1 and 2, the first 10 terms will be:
    ///      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///  By considering the terms in the Fibonacci sequence whose values do not exceed
    ///  four million, find the sum of the even-valued terms.
    let mut t1: u64 = 1;
    let mut t2: u64 = 2;
    let mut total: u64 = 0;
    while t2 <= 4000000 {
        if t2 % 2 == 0 {
            total += t2;
        }
        t2 = t1 + t2;
        t1 = t2 - t1;
    }
    total
}

fn main() {
    println!("{}", p1(10));
    println!("{}", p1_iterate(10));
    println!("{}", p1(1000));
    println!("{}", p1_iterate(1000));
    println!("{}", p2());
}
